name: 'Environment variables to Dotenv'
description: 'Appends environment variables to a dotenv file'
inputs:
  variableName:
    description: ''
    required: false
  variableNames:
    description: ''
    required: false
  variableNamesByFilter:
    description: ''
    required: false
  envPath:
    description: 'File path to write variable to'
    required: false
    default: '.env'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'gray-dark'
