name: Releases
on:
  push:
    branches:
      - main

jobs:
  releases:
    name: Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
