name: Test
on:
  pull_request:
    branches:
      - main

env:
  ENV_VAR1: 'value'
  ENV_VAR2: 'value2'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - run: yarn install --pure-lockfile
      - run: yarn test
      - run: yarn build

      - name: Test name
        uses: ./
        with:
          variableName: ENV_VAR1
      - run: cat .env

      - name: Test names
        uses: ./
        with:
          variableNames: ENV_VAR1,ENV_VAR2
      - run: cat .env

      - name: Test regex
        uses: ./
        with:
          variableNamesByFilter: ^ENV_(VAR.*)
      - run: cat .env
